jakarta:
  # Jakarta Utara (North Jakarta)
  jakarta_utara:
    name: "Jakarta Utara"
    bounds:
      min_lat: -6.2250
      max_lat: -6.1000
      min_lon: 106.7000
      max_lon: 106.8500

  # Jakarta Barat (West Jakarta)
  jakarta_barat:
    name: "Jakarta Barat"
    bounds:
      min_lat: -6.2500
      max_lat: -6.1250
      min_lon: 106.7000
      max_lon: 106.8000
